server:
  port: 8081
  #设置session的超时时间，单位是分钟
  servlet:
    session:
      #Duration转换字符串方式，默认为正，负以-开头，紧接着P，以下字母不区分大小写
      #D ：天 T：天和小时之间的分隔符 H ：小时  M：分钟  S：秒 每个单位都必须是数字，且时分秒顺序不能乱
      #比如P2dt3m5s   P3d  pt3h
      timeout: 1000m

spring:
  application:
    name: legao
  datasource:
    url: jdbc:mysql://localhost:3306/db_legao?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root #3er4#ER$
  thymeleaf:
    cache: false
    #配置静态资源路径，文件上传路径
  resources:
    static-locations: classpath:/static/,classpath:/uploadFile
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-column-underline: false
    capital-mode: false

logging:
  level:
    com.zxq.legao.dao.ScheduleDao: debug